### ISSUE TITLE
Allow headless server

### ISSUE THREAD

**Issue by javi11** [atrpm/emby_gdrive_autoscan#1]
First of all thanks for this amazing work, don't stop improving it :).

I think you can allow headless server authentication by using: 
```python
flow.run_console();
```

And adding some option to do the change ;)

https://github.com/atrpm/emby_gdrive_autoscan/blob/4e95bd32b262ad5b5fed26df4c362915fd0a3186/googleDriveService.py#L136

**Comment by saitoh183** [comment]
not working for me on my headless hetzner server
@javi11 , how did you get it to work? im suck on the permission to google drive failing since im not doing it on the same machine.

**Comment by atrpm** [comment]
Added support for headless severs... make sure to set the headless property to true in the config file.
