### ISSUE TITLE
New files not found if value of changesStartDate from config.json is not changed

### ISSUE THREAD

**Issue by titooo7** [atrpm/emby_gdrive_autoscan#3]
By default its's  `"changesStartDate": "2019-09-04T00:00:00",` but if we leave it that way then it tries to scan everything we added since then.

If I change the value to 2020-01-17T00:00:00 or even 2019-12-31T00:00:00 then the emby_gdrive_autoscan doesn't found new files added.

**Comment by atrpm** [comment]
Google API doesn't support date filter, all the filtering is done by the script.

It has to loop through all the changes since the creation date of the drive, it will catch up eventually and find changes that occurred after the set date.
